version: '3.8'

services:
  quizz_db:
    image: postgres:15-alpine
    container_name: quizz_postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/db/db_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./api/db/db_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  quizz_api:
    build: ./api
    container_name: quizz_node_api
    restart: always
    env_file: .env
    ports:
      - "${API_PORT}:${API_PORT}" 
    environment:
      - PORT=${API_PORT}
    depends_on:
      quizz_db:
        condition: service_healthy 

volumes:
  pgdata: